FROM 885134767910.dkr.ecr.ap-south-1.amazonaws.com/images:20.11.1-alpine AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json package-lock.json ./
RUN  npm install --legacy-peer-deps

FROM 885134767910.dkr.ecr.ap-south-1.amazonaws.com/images:20.11.1-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .
COPY vite.config.ts ./
COPY environments/.env.development ./.env

ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

FROM 885134767910.dkr.ecr.ap-south-1.amazonaws.com/images:20.11.1-alpine AS runner

WORKDIR /app

RUN npm install -g serve

ENV NODE_ENV development
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 vitejs

COPY --from=builder --chown=vitejs:nodejs /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/vite.config.ts ./vite.config.ts
COPY --from=builder /app/public ./public

EXPOSE 8080

ENV PORT 8080

CMD ["serve", "-s", "dist", "-l", "8080"]